name: pytorch_geometric
channels:
  - pyg
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - networkx
  - scikit-learn
  - tqdm
  - plotly
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda
  - pyg
  - pip
  - pip:
    - torch_scatter
    - torch_sparse
    - torch_cluster
    - torch_spline_conv